version: '3.3'
services:
  db:
    image: postgres:13.1
    environment:
      POSTGRES_USER: db
      POSTGRES_PASSWORD: db
      POSTGRES_DB: db
#      to persist data when container is stopped
      DB_VENDOR: postgres
    ports:
      - '5433:5432'
  api:
# OR YOUR IMAGE URL
    build: ./backend/api
    environment:
      SPRING_PROFILES_ACTIVE: local
      DB_URL: jdbc:postgresql://db:5432/db
      DB_HOST: db
      EGRESS_HOST: mock-api:8080
    ports:
      - '8888:8888'
    depends_on:
      - db
  ui:
    build: ./ui
    ports:
      - '3006:3005'
    volumes:
      - ./ui/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./ui/public/index.html:/usr/share/nginx/html/index.html
      - ./ui/public/css:/usr/share/nginx/html/css
    depends_on:
      - api
  mock-api:
    image: rodolpheche/wiremock:latest
    volumes:
      - ./_wiremock/mappings:/home/wiremock/mappings
    ports:
      - '8090:8080'